version: '3.8'

services:
  app:
    build: ../back-end/
    container_name: ai-search-backend
    environment:
      - MONGO_URL=mongodb://postgres:5432/AISearch
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres
      - PG_DATABASE_NAME=AISearch
      - PG_PORT=5432
      - PORT=4000
      - NODE_ENV=development
    ports:
      - '4000:4000'
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AISearch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data: