import { Item } from "src/types/item"
  
export const mockItems: Item[] = [
    {
      id: 1,
      name: "Image processing AI",
      url: "https://www.placebear.com",
      subtitle: "The generative AI for image processing",
      description: "Generative AI made by some company. Features multiple different nice features for lorem ipsum and image generation",
      createdAt: "2024-05-11T19:08:30.566Z",
      updatedAt: "2024-05-11T19:08:30.566Z",
      imageId: 1,
      imageName: "200/300",
      rating: 3.8333333,
      views: 0,
      saves: 0,
      ratedCount: 6,
      labels: ["3D", "2D", "Model"]
    },
    {
      id: 2,
      name: "Data analysis AI",
      url: "https://www.placebear.com",
      subtitle: "The innovative AI for data analysis",
      description: "Innovative AI tool designed for advanced data analysis. Features include lorem ipsum generation and data visualization.",
      createdAt: "2024-05-12T12:15:30.123Z",
      updatedAt: "2024-05-12T12:15:30.123Z",
      imageId: 2,
      imageName: "300/300",
      rating: 1.2,
      views: 100,
      saves: 20,
      ratedCount: 10,
      labels: ["AI", "Data Analysis", "Visualization"]
    },
    {
      id: 3,
      name: "NLP AI",
      url: "https://www.placebear.com",
      subtitle: "The AI for natural language processing",
      description: "Advanced AI tool for natural language processing tasks. Includes features for text analysis and generation.",
      createdAt: "2024-05-13T08:45:00.567Z",
      updatedAt: "2024-05-13T08:45:00.567Z",
      imageId: 3,
      imageName: "300/400",
      rating: 2.5,
      views: 150,
      saves: 25,
      ratedCount: 15,
      labels: ["AI", "NLP", "Text Analysis"]
    },
    {
      id: 4,
      name: "Image AI",
      url: "https://www.placebear.com",
      subtitle: "The AI for image recognition",
      description: "State-of-the-art AI tool for image recognition tasks. Utilizes deep learning algorithms for accurate recognition.",
      createdAt: "2024-05-14T10:30:20.890Z",
      updatedAt: "2024-05-14T10:30:20.890Z",
      imageId: 4,
      imageName: "600/600",
      rating: 2,
      views: 200,
      saves: 35,
      ratedCount: 20,
      labels: ["AI", "Image Recognition", "Deep Learning"]
    },
    {
      id: 5,
      name: "Financial AI",
      url: "https://www.placebear.com",
      subtitle: "The AI for financial forecasting",
      description: "Advanced AI tool for financial forecasting and analysis. Helps businesses make data-driven decisions.",
      createdAt: "2024-05-15T15:20:40.345Z",
      updatedAt: "2024-05-15T15:20:40.345Z",
      imageId: 5,
      imageName: "600/650",
      rating: 4.0,
      views: 250,
      saves: 40,
      ratedCount: 25,
      labels: ["AI", "Finance", "Forecasting"]
    },
    {
      id: 6,
      name: "Medical AI",
      url: "https://www.placebear.com",
      subtitle: "The AI for medical diagnosis",
      description: "Cutting-edge AI tool for medical diagnosis and analysis. Provides accurate insights for healthcare professionals.",
      createdAt: "2024-05-16T18:10:50.789Z",
      updatedAt: "2024-05-16T18:10:50.789Z",
      imageId: 6,
      imageName: "200/250",
      rating: 4.8,
      views: 300,
      saves: 45,
      ratedCount: 30,
      labels: ["AI", "Medical", "Diagnosis"]
    },
    {
      id: 7,
      name: "Customer service AI",
      url: "https://www.placebear.com",
      subtitle: "The AI for customer service",
      description: "AI-powered customer service tool that provides personalized support and assistance to users.",
      createdAt: "2024-05-17T20:00:00.456Z",
      updatedAt: "2024-05-17T20:00:00.456Z",
      imageId: 7,
      imageName: "300/250",
      rating: 1,
      views: 350,
      saves: 50,
      ratedCount: 35,
      labels: ["AI", "Customer Service", "Support"]
    },
    {
      id: 8,
      name: "Virtual Assistant AI",
      url: "https://www.placebear.com",
      subtitle: "The AI for virtual assistants",
      description: "Powerful AI platform for creating virtual assistants and chatbots. Enhance user experience with AI-driven interactions.",
      createdAt: "2024-05-18T22:30:10.987Z",
      updatedAt: "2024-05-18T22:30:10.987Z",
      imageId: 8,
      imageName: "300/350",
      rating: 4.6,
      views: 400,
      saves: 0,
      ratedCount: 40,
      labels: ["AI", "Virtual Assistant", "Chatbot"]
    },
  ]